[package]
name = "space-invaders-bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
space-invaders-core = { path = "../space-invaders-core" }
